import { parseDateInput } from "@/features/shared/lib/date-utils";

export const caseMapper = {
  toDomain(raw) {
    if (!raw) return null;
    // Extract first complaint (form uses single complaint per case)
    const rawComplaint = raw.caseComplaints?.[0];
    const complaint = rawComplaint ? {
      affectsPerson: rawComplaint.affectsPerson,
      affectsCommunity: rawComplaint.affectsCommunity,
      affectsThirdParties: rawComplaint.affectsThirdParties,
      involvedParties: rawComplaint.involvedParties,
      incidentDate: rawComplaint.incidentDate,
      popularInstance: rawComplaint.popularInstance,
      instanceRif: rawComplaint.instanceRif,
      financingEntity: rawComplaint.financingEntity,
      projectName: rawComplaint.projectName,
      approvedAmount: rawComplaint.approvedAmount,
    } : null;

    return {
      id: raw.id,
      requestNumber: raw.requestNumber,
      description: raw.description,
      caseDate: raw.caseDate,
      caseTime: raw.caseTime,
      personId: raw.personId,
      personName: raw.person ? `${raw.person.firstName} ${raw.person.lastName || ""}`.trim() : null,
      personIdCard: raw.person?.idCard || null,
      userId: raw.userId,
      userName: raw.user ? `${raw.user.firstName} ${raw.user.lastName || ""}`.trim() : null,
      caseStatusId: raw.caseStatusId,
      caseStatusName: raw.caseStatus?.name || null,
      caseAreaId: raw.caseAreaId,
      caseAreaName: raw.caseArea?.name || null,
      reasonId: raw.reasonId,
      reasonName: raw.reason?.name || null,
      attentionTypeId: raw.attentionTypeId,
      attentionTypeName: raw.attentionType?.name || null,
      attentionTypeDetailId: raw.attentionTypeDetailId,
      attentionTypeDetailName: raw.attentionTypeDetail?.name || null,
      attentionChannelId: raw.attentionChannelId,
      attentionChannelName: raw.attentionChannel?.name || null,
      attachedEntityId: raw.attachedEntityId,
      attachedEntityName: raw.attachedEntity?.name || null,
      popularOrganizationId: raw.popularOrganizationId,
      popularOrganizationName: raw.popularOrganization?.name || null,
      officeId: raw.officeId,
      officeName: raw.office?.name || null,
      complaint,
      createdAt: raw.createdAt,
      updatedAt: raw.updatedAt,
    };
  },

  toDomainList(list) {
    if (!list) return [];
    return list.map(this.toDomain);
  },

  toPersistence(domain) {
    return {
      // requestNumber is auto-generated by the repository on create — not set here
      description: domain.description?.trim() || null,
      caseDate: parseDateInput(domain.caseDate),
      caseTime: domain.caseTime?.trim() || null,
      personId: domain.personId ? Number(domain.personId) : null,
      userId: domain.userId || null,
      caseStatusId: domain.caseStatusId ? Number(domain.caseStatusId) : null,
      caseAreaId: domain.caseAreaId ? Number(domain.caseAreaId) : null,
      reasonId: domain.reasonId ? Number(domain.reasonId) : null,
      attentionTypeId: domain.attentionTypeId ? Number(domain.attentionTypeId) : null,
      attentionTypeDetailId: domain.attentionTypeDetailId ? Number(domain.attentionTypeDetailId) : null,
      attentionChannelId: domain.attentionChannelId ? Number(domain.attentionChannelId) : null,
      attachedEntityId: domain.attachedEntityId ? Number(domain.attachedEntityId) : null,
      popularOrganizationId: domain.popularOrganizationId ? Number(domain.popularOrganizationId) : null,
      officeId: domain.officeId ? Number(domain.officeId) : null,
    };
  },

  toSortKey(domainKey) {
    const map = {
      requestNumber: "requestNumber",
      caseDate: "caseDate",
      createdAt: "createdAt",
    };
    return map[domainKey] || "createdAt";
  },
};
