/**
 * Business rules validation for cases.
 * requestNumber is auto-generated by the repository — no uniqueness check needed here.
 */
export async function validateCaseRules(data, excludeId = null) {
  // Future validations can be added here (e.g., required fields per attention type)

  return { success: true };
}
